      name: botkube_app
      description: "Botkube Flutter Application"
      version: 1.0.0+1

      environment:
        sdk: '>=3.0.0 <4.0.0'

      dependencies:
        flutter:
          sdk: flutter
        flutter_localizations:
          sdk: flutter
        intl: ^0.19.0
        http: ^1.1.0
        flutter_dotenv: ^5.1.0
        provider: ^6.0.5
        flutter_gen: ^5.10.0
        web_socket_channel: ^2.4.0
        shared_preferences: ^2.2.0
        timeago: ^3.5.0
        flutter_syntax_view: ^4.0.0
        path_provider: ^2.1.0
        url_launcher: ^6.1.14

      dev_dependencies:
        flutter_test:
          sdk: flutter
        flutter_lints: ^2.0.0
        build_runner: ^2.4.6
        flutter_gen_runner: ^5.3.1

      flutter:
        generate: true
        uses-material-design: true
        assets:
          - .env
          - images/
          - fonts/
        # Fonts section commented out until font files are added
        # fonts:
        #   - family: Roboto
        #     fonts:
        #       - asset: fonts/Roboto-Regular.ttf
        #       - asset: fonts/Roboto-Bold.ttf
        #         weight: 700
        #       - asset: fonts/Roboto-Light.ttf
        #         weight: 300
        #       - asset: fonts/Roboto-Medium.ttf
        #         weight: 500

      # The following adds the Cupertino Icons font to your application.
      # Use with the CupertinoIcons class for iOS style icons.
      cupertino_icons: ^1.0.2
